-- MySQL Script generated by MySQL Workbench
-- Sat Mar 19 18:17:37 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema urs_test
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `urs_test` ;

-- -----------------------------------------------------
-- Schema urs_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `urs_test` DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;
USE `urs_test` ;

-- -----------------------------------------------------
-- Table `urs_test`.`some_parent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urs_test`.`some_parent` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `modify_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urs_test`.`some_child`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urs_test`.`some_child` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `modify_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_child_parent_idx` (`parent` ASC),
  CONSTRAINT `fk_child_parent`
    FOREIGN KEY (`parent`)
    REFERENCES `urs_test`.`some_parent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urs_test`.`some_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urs_test`.`some_type` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urs_test`.`some_super`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urs_test`.`some_super` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `some_type` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `create_utc` BIGINT NOT NULL,
  `update_utc` BIGINT NOT NULL,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `FK_SOME_SUPER_PK_SOME_TIME` (`some_type` ASC),
  CONSTRAINT `FK_SOME_SUPER_PK_SOME_TIME`
    FOREIGN KEY (`some_type`)
    REFERENCES `urs_test`.`some_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urs_test`.`some_sub1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urs_test`.`some_sub1` (
  `some_super` INT UNSIGNED NOT NULL,
  `some_text` VARCHAR(45) NOT NULL,
  `create_utc` BIGINT NOT NULL,
  `update_utc` BIGINT NOT NULL,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`some_super`),
  CONSTRAINT `FK_SOME_SUB1_PK_SOME_SUPER`
    FOREIGN KEY (`some_super`)
    REFERENCES `urs_test`.`some_super` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urs_test`.`some_sub2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urs_test`.`some_sub2` (
  `some_super` INT UNSIGNED NOT NULL,
  `some_int` VARCHAR(45) NULL,
  `create_utc` BIGINT NOT NULL,
  `update_utc` BIGINT NOT NULL,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`some_super`),
  CONSTRAINT `FK_SOME_SUB2_PK_SOME_SUPER`
    FOREIGN KEY (`some_super`)
    REFERENCES `urs_test`.`some_super` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `urs_test`.`some_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `urs_test`;
INSERT INTO `urs_test`.`some_type` (`id`, `name`, `modified_at`) VALUES (0, 'SomeSub1', DEFAULT);
INSERT INTO `urs_test`.`some_type` (`id`, `name`, `modified_at`) VALUES (1, 'SomeSub2', DEFAULT);

COMMIT;

